  version : "3"
  services:

    eureka-service:
      image: eurekaservice-app
      build: eureka-registry-service/
      restart: always
      network_mode: host
      container_name: eureka-service-docker
      ports:
        - "8761:8761"
      expose:
        - 8761

    mongo:
      image: mongo
      ports:
        - "27017:27017"
      container_name: mongo
      network_mode: host

    spring-config-server:
      image: configservice-app
      build: spring-config-server/
      restart: always
      network_mode: host
      container_name: config-service
      ports:
        - "8888:8888"
      expose:
        - 8888
    api-gateway-service:
      image: apigatewayservice-app
      build: api-gateway-service/
      restart: always
      network_mode: host
      container_name: apigateway-service-docker
      ports:
        - "8087:8087"
      expose:
        - 8087
    muzizapplication:
      image: trackservice-app
      build: muzixapplication/
      restart: always
      network_mode: host
      container_name: track-service-docker
      depends_on:
        - mongo
        - spring-config-server
      ports:
        - "8081:8081"
      expose:
        - 8081
    user-profile:
      image: userservice-app
      build: user-profile/
      restart: always
      network_mode: host
      container_name: user-service-docker
      depends_on:
        - mongo
        - spring-config-server
      ports:
        - "8082:8082"
      expose:
        - 8082